-- проверка 1

select * from so_ru.TAGSYNONYMS where SOURCETAGNAME = 'c++' or TARGETTAGNAME = 'c++';

SELECT * FROM DIM_TAG WHERE TAG_NAME = 'c++';
SELECT * FROM DIM_DATE WHERE DATE_NAME = '07.11.2013'; -- 1458
SELECT * FROM DIM_DATE WHERE DATE_NAME = '11.2013'; -- 1452
SELECT * FROM DIM_DATE WHERE DATE_NAME = '2013'; -- 1138

SELECT * FROM STG_DATE_TAG_AGGS WHERE TAG_ID = 466 AND DATE_ID = 1458;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<с++>%' OR TAGS LIKE '%<cpp>%' OR TAGS LIKE '%<c++>%')
  AND TRUNC(CREATIONDATE) = TO_DATE('07.11.2013', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

select * from AGG_QUESTIONS where TAG_ID = 466 and DATE_ID = 1452;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<с++>%' OR TAGS LIKE '%<cpp>%' OR TAGS LIKE '%<c++>%')
  AND TRUNC(CREATIONDATE, 'month') = TO_DATE('01.11.2013', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

select * from AGG_QUESTIONS where TAG_ID = 466 and DATE_ID = 1138;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<с++>%' OR TAGS LIKE '%<cpp>%' OR TAGS LIKE '%<c++>%')
  AND TRUNC(CREATIONDATE, 'year') = TO_DATE('01.01.2013', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

-- проверка 2

select TARGETTAGNAME, count(*) from so_ru.TAGSYNONYMS group by TARGETTAGNAME order by count(*) desc;

select * from so_ru.TAGSYNONYMS where SOURCETAGNAME = 'javascript' or TARGETTAGNAME = 'javascript';

SELECT * FROM DIM_TAG WHERE TAG_NAME = 'javascript'; -- 1590
SELECT * FROM DIM_DATE WHERE DATE_NAME = '21.03.2017'; -- 2732
SELECT * FROM DIM_DATE WHERE DATE_NAME = '03.2017'; -- 2712
SELECT * FROM DIM_DATE WHERE DATE_NAME = '2017'; -- 2651

SELECT * FROM STG_DATE_TAG_AGGS WHERE TAG_ID = 1590 AND DATE_ID = 2732;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<js>%' OR TAGS LIKE '%<php>%' OR TAGS LIKE '%<javascript>%')
  AND TRUNC(CREATIONDATE) = TO_DATE('21.03.2017', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

select * from AGG_QUESTIONS where TAG_ID = 1590 and DATE_ID = 2712;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<js>%' OR TAGS LIKE '%<php>%' OR TAGS LIKE '%<javascript>%')
  AND TRUNC(CREATIONDATE, 'month') = TO_DATE('01.03.2017', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

select * from AGG_QUESTIONS where TAG_ID = 1590 and DATE_ID = 2651;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<js>%' OR TAGS LIKE '%<php>%' OR TAGS LIKE '%<javascript>%')
  AND TRUNC(CREATIONDATE, 'year') = TO_DATE('01.01.2017', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

-- проверка 3 (по всем тегам за какое-то время)
-- аггрегация по всем тегам за какое-то время не будет работать потому что у
-- каждого вопроса по-несколько тегов и, поэтому, некоторые вопросы участвуют
-- в аггрегации дважды, трижды и т.д.

select * from AGG_QUESTIONS where TAG_ID is null and DATE_ID = 2651;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND TRUNC(CREATIONDATE, 'year') = TO_DATE('01.01.2017', 'DD.MM.YYYY')
ORDER BY CREATIONDATE;

-- проверка 4 (по всем тегам за какое-то время)

select * from AGG_QUESTIONS where TAG_ID = 1590 and DATE_ID is null;

SELECT
    AVG(SCORE)       AVG_SCORE,
    MIN(SCORE)       MIN_SCORE,
    MAX(SCORE)       MAX_SCORE,
    AVG(VIEWCOUNT)  AVG_VIEW_COUNT,
    MAX(VIEWCOUNT)  MAX_VIEW_COUNT,
    MIN(VIEWCOUNT)  MIN_VIEW_COUNT,
    SUM(VIEWCOUNT)  TOTAL_VIEW_COUNT,
    COUNT(*)         QUESTIONS_COUNT
FROM
    SO_RU.POSTS
WHERE
        POSTTYPEID = 1
  AND (TAGS LIKE '%<js>%' OR TAGS LIKE '%<php>%' OR TAGS LIKE '%<javascript>%')
ORDER BY CREATIONDATE;